/* DO NOT EDIT THIS FILE. THIS FILE WAS GENERATED FROM org/nongnu/libvob/lob/Components.rj,
 * EDIT THAT FILE INSTEAD!
 * All changes to this file will be lost.
 *//* -*-java-*-
Components.rj
 *    
 *    Copyright (c) 2005, Benja Fallenstein
 *
 *    This file is part of Libvob.
 *    
 *    Libvob is free software; you can redistribute it and/or modify it under
 *    the terms of the GNU General Public License as published by
 *    the Free Software Foundation; either version 2 of the License, or
 *    (at your option) any later version.
 *    
 *    Libvob is distributed in the hope that it will be useful, but WITHOUT
 *    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 *    or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
 *    Public License for more details.
 *    
 *    You should have received a copy of the GNU General
 *    Public License along with Libvob; if not, write to the Free
 *    Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *    
 *
 */
/*
 * Written by Benja Fallenstein
 */
package org.nongnu.libvob.lob;
import org.nongnu.libvob.fn.*;
import org.nongnu.libvob.lob.lobs.*;
import javolution.lang.*;
import javolution.realtime.*;
import java.awt.Color;
import java.util.*;

public class Components {

    public static Model getModel(Map params, String name, Object _default) {
	return (Model)getParam(params, name, 
			       StateModel.newInstance(name, _default));
    }

    public static Model getModel(Map params, String name, int _default) {
	return (Model)getParam(params, name, 
			       StateModel.newInstance(name, _default));
    }

    public static Object getParam(Map params, String name, Object _default) {
	if(params.get(name) != null)
	    return params.get(name);
	else
	    return _default;
    }



    public static Color 
	lightColor = new java.awt.Color(1, 1, .9f),
	darkColor = new java.awt.Color(.7f, .5f, .5f);




    public static Lob frame(Lob lob) {
	return Lobs.frame(lob, lightColor, darkColor, 1, 3, true);
    }

    public static Lob button(Lob content, Action action) {
	Lob lob = content;
	lob = Lobs.align(content, .5f, .5f);
	lob = Lobs.request(lob, 50, -1, SizeRequest.INF,
			   15, -1, SizeRequest.INF);
	lob = frame(lob);
	lob = Lobs.clickController(lob, 1, action);
	return lob;
    }

    public static Lob listBox(List elements, Map params) {
	Transform tr = (Transform)getParam(params, "transform", 
					   toStringTransform());

	Object defaultSelection = elements.size() > 0 ? elements.get(0) : null;
	Model selected = getModel(params, "selected", defaultSelection);

	Axis axis = (Axis)getParam(params, "axis", Axis.Y);

	tr = new_Transform_1(tr,selected);

	List lobs = Lists.transform(elements, tr);
	Lob glue = Lobs.glue(axis, 0, 0, SizeRequest.INF);
	lobs = Lists.concat(lobs, Lists.list(glue));

	Lob lob = Lobs.box(axis, lobs);
	
        Lob cursor_lob = Lobs.filledRect(darkColor);
        cursor_lob = Lobs.key(cursor_lob, "cursor");
        lob = Lobs.decorate(lob, cursor_lob, selected.get(), -1);

	lob = frame(lob);
	return lob;
    }

    public static Lob textBox(Model text, Map params) {
	params.put("multiline", Boolean.FALSE);
	return textComponent(text, params);
    }

    public static Lob textArea(Model text, Map params) {
	params.put("multiline", Boolean.TRUE);
	return textComponent(text, params);
    }

    public static Lob textComponent(Model text, Map params) {

	Model cursor = (Model)getModel(params, "cursor", -1);
	LobFont font = (LobFont)getParam(params, "font", Lobs.font());

	Boolean multilineB = (Boolean)getParam(params, "multiline", null);
	boolean multiline = multilineB.booleanValue();

	Text txt = Text.valueOf((String)text.get());
	List list = Lobs.text(font, txt);
	list = Lobs.keyList(list, "text");
	Lob lob = multiline ? Lobs.linebreaker(list) : Lobs.hbox(list);

        Lob cursor_lob = Lobs.line(java.awt.Color.black, 0, 0, 0, 1);
        cursor_lob = Lobs.key(cursor_lob, "textcursor");
        lob = Lobs.decorate(lob, cursor_lob, "text", cursor.getInt());
	
        lob = TextKeyController.newInstance(lob, text, cursor);

	return frame(lob);
    }
    
    public static Lob menuitem(String s, Action action) {
	return menuitem(Lobs.hbox(Lobs.text(s)), action);
    }

    public static Lob menuitem(Lob lob, Action action) {
	Action _action = action; // XXX close menu if necessary!

	lob = Lobs.margin(lob, 8, 2);
	return Lobs.clickController(lob, 1, _action);
    }

    public static Lob menuitem(String s, Lob submenu) {
	return menuitem(Lobs.hbox(Lobs.text(s)), submenu);
    }

    public static Lob menuitem(Lob lob, Lob submenu) {
	Model openModel = StateModel.newInstance("open", Boolean.FALSE);

	Action action = new_Action_2(openModel);

	lob = Lobs.margin(lob, 8, 2);

	if(openModel.get() == Boolean.TRUE)
	    lob = Lobs.nextTo(Axis.Y, lob, submenu);
	    
	lob = Lobs.clickController(lob, 1, action);

	return lob;
    }

    public static Lob menubar() {
	return menu(Axis.X, Lists.list());
    }

    public static Lob menu() {
	return menu(Axis.Y, Lists.list());
    }

    public static Lob menu(Axis axis, List items) {
	Lob l = Lobs.box(axis, items);
	l = Lobs.align(l, 0, 0);
	l = Lobs.frame3d(l, lightColor, darkColor, 1, 0, false, true);
	l = Lobs.frame(l, null, darkColor, 1, 0, true);

	return l;
    }


    public static Transform toStringTransform() {
	return new_Transform_3();
    }

        private static class _Transform_1 extends RealtimeObject implements Transform {

            private _Transform_1() {}

            Transform tr; Model selected;

            
	    public Object transform(Object o) {
		Lob lob = (Lob)tr.transform(o);
		lob = Lobs.margin(lob, 1);

		Action select = new_Action_4(selected,o);

		lob = Lobs.clickController(lob, 1, select);
                    
		return Lobs.key(lob, o);
	    }
	

            public boolean move(ObjectSpace os) {
                if(super.move(os)) {
                    if(tr instanceof Realtime) ((Realtime)tr).move(os); if(selected instanceof Realtime) ((Realtime)selected).move(os); 
                    return true;
                }
                return false;
            }
        }

        private static final RealtimeObject.Factory _Transform_1_FACTORY =
            new RealtimeObject.Factory() {
                protected Object create() { return new _Transform_1(); }
            };

        private static _Transform_1 new_Transform_1(Transform tr, Model selected) {
            _Transform_1 the_new_Transform_1 = (_Transform_1)_Transform_1_FACTORY.object();
            the_new_Transform_1.tr = tr;
the_new_Transform_1.selected = selected;
            return the_new_Transform_1;
        }
    
        private static class _Action_2 extends RealtimeObject implements Action {

            private _Action_2() {}

            Model openModel;

            
	    public void run() {
		Boolean open = (Boolean)openModel.get();
		if(open == Boolean.FALSE) {
		    openModel.set(Boolean.TRUE);
		} else {
		    openModel.set(Boolean.FALSE);
		}
	    }
	

            public boolean move(ObjectSpace os) {
                if(super.move(os)) {
                    if(openModel instanceof Realtime) ((Realtime)openModel).move(os); 
                    return true;
                }
                return false;
            }
        }

        private static final RealtimeObject.Factory _Action_2_FACTORY =
            new RealtimeObject.Factory() {
                protected Object create() { return new _Action_2(); }
            };

        private static _Action_2 new_Action_2(Model openModel) {
            _Action_2 the_new_Action_2 = (_Action_2)_Action_2_FACTORY.object();
            the_new_Action_2.openModel = openModel;
            return the_new_Action_2;
        }
    
        private static class _Transform_3 extends RealtimeObject implements Transform {

            private _Transform_3() {}

            ;

            
	    public Object transform(Object o) {
		if(o instanceof Realtime)
		    return Lobs.hbox(Lobs.text(((Realtime)o).toText()));
		else
		    return Lobs.hbox(Lobs.text(o.toString()));
	    }
	

            public boolean move(ObjectSpace os) {
                if(super.move(os)) {
                    
                    return true;
                }
                return false;
            }
        }

        private static final RealtimeObject.Factory _Transform_3_FACTORY =
            new RealtimeObject.Factory() {
                protected Object create() { return new _Transform_3(); }
            };

        private static _Transform_3 new_Transform_3() {
            _Transform_3 the_new_Transform_3 = (_Transform_3)_Transform_3_FACTORY.object();
            
            return the_new_Transform_3;
        }
    
        private static class _Action_4 extends RealtimeObject implements Action {

            private _Action_4() {}

            Model selected;
						       Object o;

            
		    public void run() {
			selected.set(o);
		    }
		

            public boolean move(ObjectSpace os) {
                if(super.move(os)) {
                    if(selected instanceof Realtime) ((Realtime)selected).move(os); if(o instanceof Realtime) ((Realtime)o).move(os); 
                    return true;
                }
                return false;
            }
        }

        private static final RealtimeObject.Factory _Action_4_FACTORY =
            new RealtimeObject.Factory() {
                protected Object create() { return new _Action_4(); }
            };

        private static _Action_4 new_Action_4(Model selected,
						       Object o) {
            _Action_4 the_new_Action_4 = (_Action_4)_Action_4_FACTORY.object();
            the_new_Action_4.selected = selected;
the_new_Action_4.o = o;
            return the_new_Action_4;
        }
    }
